---
name: CI

on:
  push:

jobs:
  precommit:
    name: pre-commit checks
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Install requirements
        run: pip install pre-commit
      - name: Run pre-commit hooks
        run: |
          merge_base=$(git merge-base -a HEAD origin/main)
          changed_files=$(git diff --name-only $merge_base...HEAD)
          echo "Changed files since branched from origin/main: " $changed_files
          git reset --soft $merge_base
          pre-commit run --show-diff-on-failure --files $changed_files
